theme: jekyll-theme-slate
name: Home
description: ""
title: Hi, I'm Michael ğŸ‘‹ğŸ¼
subtitle: ""
site_header_image: './cropped-background.jpg'
  
# generate social links in footer
social_links:
twitter: maybe_social
github:  michael-r-may
stack-overflow: 593632/michael
linkedin: may-michael
